[package]
name = "view"
version = "0.1.0"


[dependencies]
shared = { path = "../shared" }
piston = "0.53.1"
piston_window = "0.124.0"
find_folder = "0.3.0"
piston2d-sprite = "0.66.0"

[lib]
crate-type = ["rlib", "dylib"]
path = "src/view.rs"